 
 /*------------------------------------------------------------------------
    File        : IAmmo
    Purpose     : Additional layer for Binding 
    Syntax      : 
    Description : 
    Author(s)   : Boehme_A
    Created     : Fri Dec 14 12:15:47 CET 2018
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

interface OpenEdge.Test.IAmmo:  
    
    method public integer iImpact().
    
    method public void Unpack().
    
end interface.