/*------------------------------------------------------------------------
    File        : IArmor
    Purpose     : Ninja armor interface
    Syntax      : 
    Description : 
    Author(s)   : Boehme_A
    Created     : Sat Dec 15 13:19:38 CET 2018
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

interface OpenEdge.Test.IArmor:  
    
    method public integer iProtect().
    
end interface.