
/*------------------------------------------------------------------------
    File        : IWeapon
    Purpose     : 
    Syntax      : 
    Description : 
    @author pjudge
    Created     : Tue Mar 02 10:59:20 EST 2010
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

interface OpenEdge.Test.IWeapon:  
    
    method public void Hit(target as char).
    
end interface.