 
 /*------------------------------------------------------------------------
    File        : S2
    Purpose     : 
    Syntax      : 
    Description : 
    @author pjudge
    Created     : Mon Nov 16 15:51:08 EST 2009
    Notes       : 
  ----------------------------------------------------------------------*/
using OpenEdge.Test.*.
using Progress.Lang.*.

block-level on error undo, throw.

class OpenEdge.Test.S2 :

    def protected var TextField as char init 'aaa'.
     

end class.